# b/.gitlab-ci.yml

stages:
  - build
  - deploy

build:
  stage: build && sleep 10
  script: echo Build service B

deploy:
  stage: deploy
  script: echo Deploy service B && false


deploy2:
  stage: deploy
  script: echo Deploy service B

deploy3:
  stage: deploy
  script: echo Deploy service B

deploy4:
  stage: deploy
  script: echo Deploy service B

deploy5:
  stage: deploy
  script: echo Deploy service B

deploy6:
  stage: deploy
  script: echo Deploy service B
