stages:
  - generate
  - pipeline

generate:
  stage: generate
  image: python:3.7-slim
  script: python generate-gitlab-ci.py
  artifacts:
    paths:
      - .gitlab-ci.generated.yml

pipeline:
  stage: pipeline
  trigger:
    include:
      - artifact: .gitlab-ci.generated.yml
        job: generate
    strategy: depend

triger-pipelines:
  stage: .pre
  trigger: test/mirek

triger-pipelines2:
  stage: .pre
  trigger:
    project: test/mirek
    strategy: depend

triger-pipelines3:
  stage: .pre
  trigger:
    project: test/jh
    strategy: depend
